import jsPDF from 'jspdf';
import { formatDate } from '@/lib/utils';

type DocumentWithRelations = {
  type: string;
  content: string;
  consultation: {
    status: string;
    consultationDate: Date;
    patient: {
      firstName: string;
      lastName: string;
      dateOfBirth: Date | null;
      gender: string | null;
      medicalRecordNumber: string | null;
    };
  };
  doctor: { name: string };
};

export function buildPdfBuffer(document: DocumentWithRelations): Buffer {
  const hospitalName = process.env.HOSPITAL_NAME || 'Medical Center';
  const isDraft = document.consultation.status === 'draft' || document.consultation.status === 'in_progress';

  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  pdf.setDrawColor(200, 200, 200);
  pdf.rect(margin, yPosition, 18, 18);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Logo', margin + 5, yPosition + 12);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(hospitalName, margin + 22, yPosition + 8);
  pdf.setFontSize(12);
  pdf.text(
    document.type === 'discharge_summary' ? 'DISCHARGE SUMMARY' : 'CASE SHEET',
    margin + 22,
    yPosition + 16
  );
  yPosition += 28;

  if (isDraft) {
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'italic');
    pdf.setTextColor(180, 0, 0);
    pdf.text('DRAFT - NOT FOR OFFICIAL USE', margin, yPosition);
    pdf.setTextColor(0, 0, 0);
    yPosition += 6;
  }

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Patient Information', margin, yPosition);
  yPosition += 8;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  const patientInfo = [
    ['Name:', `${document.consultation.patient.firstName} ${document.consultation.patient.lastName}`],
    ['Date of Birth:', document.consultation.patient.dateOfBirth ? formatDate(document.consultation.patient.dateOfBirth) : 'N/A'],
    ['Gender:', document.consultation.patient.gender || 'N/A'],
    ['Medical Record Number:', document.consultation.patient.medicalRecordNumber || 'N/A'],
    ['Consultation Date:', formatDate(document.consultation.consultationDate)],
  ];
  patientInfo.forEach(([label, value]) => {
    pdf.setFont('helvetica', 'bold');
    pdf.text(label, margin, yPosition);
    pdf.setFont('helvetica', 'normal');
    pdf.text(value, margin + 60, yPosition);
    yPosition += 6;
  });
  yPosition += 5;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Document Content', margin, yPosition);
  yPosition += 8;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const paragraphs = document.content.split('\n\n').filter((p) => p.trim());
  paragraphs.forEach((paragraph) => {
    const lines = pdf.splitTextToSize(paragraph.trim(), maxWidth);
    if (yPosition + lines.length * 5 > pageHeight - 30) {
      pdf.addPage();
      yPosition = margin;
    }
    lines.forEach((line: string) => {
      pdf.text(line, margin, yPosition);
      yPosition += 5;
    });
    yPosition += 3;
  });

  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'italic');
    const pageFooterY = pdf.internal.pageSize.getHeight() - 10;
    pdf.text(
      `Confidential - ${hospitalName} | Page ${i} of ${totalPages} | Generated by MedScribe`,
      pageWidth / 2,
      pageFooterY,
      { align: 'center' }
    );
    if (i === totalPages) {
      const sigY = pageFooterY - 25;
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.text('_________________________', margin, sigY);
      pdf.text(document.doctor.name, margin, sigY + 5);
      pdf.setFontSize(8);
      pdf.text('Authorized Signature', margin, sigY + 10);
    }
  }

  return Buffer.from(pdf.output('arraybuffer'));
}
