import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { formatDate } from '@/lib/utils';

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const document = await prisma.document.findFirst({
      where: {
        id: params.id,
        doctorId: session.user.id,
      },
      include: {
        consultation: { include: { patient: true } },
        doctor: { select: { name: true } },
      },
    });

    if (!document) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 });
    }

    const patient = document.consultation.patient;
    const patientName = `${patient.firstName} ${patient.lastName}`;
    const contentHtml = document.content
      .split(/\n\n+/)
      .map((p) => `<p>${p.replace(/\n/g, '<br/>')}</p>`)
      .join('\n');

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${document.type === 'discharge_summary' ? 'Discharge Summary' : 'Case Sheet'} - ${patientName}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #222; }
    h1 { font-size: 1.5rem; border-bottom: 1px solid #ccc; padding-bottom: 0.5rem; }
    .meta { color: #555; margin-bottom: 1.5rem; }
    .content p { margin: 0.5rem 0; line-height: 1.5; }
    .signature { margin-top: 2rem; }
    .confidential { font-size: 0.85rem; color: #666; margin-top: 2rem; }
  </style>
</head>
<body>
  <h1>${document.type === 'discharge_summary' ? 'Discharge Summary' : 'Case Sheet'}</h1>
  <div class="meta">
    <p><strong>Patient:</strong> ${patientName}</p>
    <p><strong>DOB:</strong> ${patient.dateOfBirth ? formatDate(patient.dateOfBirth) : 'N/A'}</p>
    <p><strong>Consultation Date:</strong> ${formatDate(document.consultation.consultationDate)}</p>
  </div>
  <div class="content">${contentHtml}</div>
  <div class="signature">
    <p>_________________________</p>
    <p>${document.doctor.name}</p>
    <p><em>Authorized Signature</em></p>
  </div>
  <p class="confidential">Confidential - For authorized use only. Generated by MedScribe.</p>
</body>
</html>`;

    const filename = `${document.type}_${patient.lastName}_${new Date().toISOString().split('T')[0]}.html`;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Error generating HTML:', error);
    return NextResponse.json(
      { error: 'Failed to generate HTML' },
      { status: 500 }
    );
  }
}
